//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySoapService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.espe.edu.ec/library", ConfigurationName="LibrarySoapService.LibraryPort")]
    public interface LibraryPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.addBookResponse1> addBookAsync(LibrarySoapService.addBookRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.deleteAuthorResponse1> deleteAuthorAsync(LibrarySoapService.deleteAuthorRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.getGenresResponse> getGenresAsync(LibrarySoapService.getGenresRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.getBookResponse1> getBookAsync(LibrarySoapService.getBookRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.updateBookResponse1> updateBookAsync(LibrarySoapService.updateBookRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.getAuthorsResponse> getAuthorsAsync(LibrarySoapService.getAuthorsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.deleteBookResponse1> deleteBookAsync(LibrarySoapService.deleteBookRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.getAuthorResponse1> getAuthorAsync(LibrarySoapService.getAuthorRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.getBooksResponse> getBooksAsync(LibrarySoapService.getBooksRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.updateGenreResponse1> updateGenreAsync(LibrarySoapService.updateGenreRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.addAuthorResponse1> addAuthorAsync(LibrarySoapService.addAuthorRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.deleteGenreResponse1> deleteGenreAsync(LibrarySoapService.deleteGenreRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.updateAuthorResponse1> updateAuthorAsync(LibrarySoapService.updateAuthorRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.addGenreResponse1> addGenreAsync(LibrarySoapService.addGenreRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LibrarySoapService.getGenreResponse1> getGenreAsync(LibrarySoapService.getGenreRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class addBookRequest
    {
        
        private BookModel bookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BookModel book
        {
            get
            {
                return this.bookField;
            }
            set
            {
                this.bookField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.espe.edu.ec/library")]
    public partial class BookModel
    {
        
        private long idField;
        
        private string titleField;
        
        private AuthorModel authorField;
        
        private int yearField;
        
        private bool yearFieldSpecified;
        
        private GenreModel[] genresField;
        
        private string publisherField;
        
        private string isbnField;
        
        private double priceField;
        
        private RequestImage imageField;
        
        private string imageUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AuthorModel author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearSpecified
        {
            get
            {
                return this.yearFieldSpecified;
            }
            set
            {
                this.yearFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("genres", Order=4)]
        public GenreModel[] genres
        {
            get
            {
                return this.genresField;
            }
            set
            {
                this.genresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string publisher
        {
            get
            {
                return this.publisherField;
            }
            set
            {
                this.publisherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string isbn
        {
            get
            {
                return this.isbnField;
            }
            set
            {
                this.isbnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public RequestImage image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string imageUrl
        {
            get
            {
                return this.imageUrlField;
            }
            set
            {
                this.imageUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.espe.edu.ec/library")]
    public partial class AuthorModel
    {
        
        private long idField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string pseudonymField;
        
        private System.DateTime birthdateField;
        
        private bool birthdateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string pseudonym
        {
            get
            {
                return this.pseudonymField;
            }
            set
            {
                this.pseudonymField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime birthdate
        {
            get
            {
                return this.birthdateField;
            }
            set
            {
                this.birthdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthdateSpecified
        {
            get
            {
                return this.birthdateFieldSpecified;
            }
            set
            {
                this.birthdateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.espe.edu.ec/library")]
    public partial class RequestImage
    {
        
        private string nameField;
        
        private string typeField;
        
        private byte[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.espe.edu.ec/library")]
    public partial class GenreModel
    {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class addBookResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addBookRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.addBookRequest addBookRequest;
        
        public addBookRequest1()
        {
        }
        
        public addBookRequest1(LibrarySoapService.addBookRequest addBookRequest)
        {
            this.addBookRequest = addBookRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addBookResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.addBookResponse addBookResponse;
        
        public addBookResponse1()
        {
        }
        
        public addBookResponse1(LibrarySoapService.addBookResponse addBookResponse)
        {
            this.addBookResponse = addBookResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class deleteAuthorRequest
    {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class deleteAuthorResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteAuthorRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.deleteAuthorRequest deleteAuthorRequest;
        
        public deleteAuthorRequest1()
        {
        }
        
        public deleteAuthorRequest1(LibrarySoapService.deleteAuthorRequest deleteAuthorRequest)
        {
            this.deleteAuthorRequest = deleteAuthorRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteAuthorResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.deleteAuthorResponse deleteAuthorResponse;
        
        public deleteAuthorResponse1()
        {
        }
        
        public deleteAuthorResponse1(LibrarySoapService.deleteAuthorResponse deleteAuthorResponse)
        {
            this.deleteAuthorResponse = deleteAuthorResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class getGenresRequest
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGenresRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.getGenresRequest getGenresRequest;
        
        public getGenresRequest1()
        {
        }
        
        public getGenresRequest1(LibrarySoapService.getGenresRequest getGenresRequest)
        {
            this.getGenresRequest = getGenresRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGenresResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGenresResponse", Namespace="https://www.espe.edu.ec/library", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("genres", IsNullable=false)]
        public LibrarySoapService.GenreModel[] getGenresResponse1;
        
        public getGenresResponse()
        {
        }
        
        public getGenresResponse(LibrarySoapService.GenreModel[] getGenresResponse1)
        {
            this.getGenresResponse1 = getGenresResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class getBookRequest
    {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class getBookResponse
    {
        
        private BookModel bookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BookModel book
        {
            get
            {
                return this.bookField;
            }
            set
            {
                this.bookField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBookRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.getBookRequest getBookRequest;
        
        public getBookRequest1()
        {
        }
        
        public getBookRequest1(LibrarySoapService.getBookRequest getBookRequest)
        {
            this.getBookRequest = getBookRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBookResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.getBookResponse getBookResponse;
        
        public getBookResponse1()
        {
        }
        
        public getBookResponse1(LibrarySoapService.getBookResponse getBookResponse)
        {
            this.getBookResponse = getBookResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class updateBookRequest
    {
        
        private BookModel bookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BookModel book
        {
            get
            {
                return this.bookField;
            }
            set
            {
                this.bookField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class updateBookResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateBookRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.updateBookRequest updateBookRequest;
        
        public updateBookRequest1()
        {
        }
        
        public updateBookRequest1(LibrarySoapService.updateBookRequest updateBookRequest)
        {
            this.updateBookRequest = updateBookRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateBookResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.updateBookResponse updateBookResponse;
        
        public updateBookResponse1()
        {
        }
        
        public updateBookResponse1(LibrarySoapService.updateBookResponse updateBookResponse)
        {
            this.updateBookResponse = updateBookResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class getAuthorsRequest
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAuthorsRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.getAuthorsRequest getAuthorsRequest;
        
        public getAuthorsRequest1()
        {
        }
        
        public getAuthorsRequest1(LibrarySoapService.getAuthorsRequest getAuthorsRequest)
        {
            this.getAuthorsRequest = getAuthorsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAuthorsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAuthorsResponse", Namespace="https://www.espe.edu.ec/library", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("author", IsNullable=false)]
        public LibrarySoapService.AuthorModel[] getAuthorsResponse1;
        
        public getAuthorsResponse()
        {
        }
        
        public getAuthorsResponse(LibrarySoapService.AuthorModel[] getAuthorsResponse1)
        {
            this.getAuthorsResponse1 = getAuthorsResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class deleteBookRequest
    {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class deleteBookResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteBookRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.deleteBookRequest deleteBookRequest;
        
        public deleteBookRequest1()
        {
        }
        
        public deleteBookRequest1(LibrarySoapService.deleteBookRequest deleteBookRequest)
        {
            this.deleteBookRequest = deleteBookRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteBookResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.deleteBookResponse deleteBookResponse;
        
        public deleteBookResponse1()
        {
        }
        
        public deleteBookResponse1(LibrarySoapService.deleteBookResponse deleteBookResponse)
        {
            this.deleteBookResponse = deleteBookResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class getAuthorRequest
    {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class getAuthorResponse
    {
        
        private AuthorModel authorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuthorModel author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAuthorRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.getAuthorRequest getAuthorRequest;
        
        public getAuthorRequest1()
        {
        }
        
        public getAuthorRequest1(LibrarySoapService.getAuthorRequest getAuthorRequest)
        {
            this.getAuthorRequest = getAuthorRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAuthorResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.getAuthorResponse getAuthorResponse;
        
        public getAuthorResponse1()
        {
        }
        
        public getAuthorResponse1(LibrarySoapService.getAuthorResponse getAuthorResponse)
        {
            this.getAuthorResponse = getAuthorResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class getBooksRequest
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBooksRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.getBooksRequest getBooksRequest;
        
        public getBooksRequest1()
        {
        }
        
        public getBooksRequest1(LibrarySoapService.getBooksRequest getBooksRequest)
        {
            this.getBooksRequest = getBooksRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBooksResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBooksResponse", Namespace="https://www.espe.edu.ec/library", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("book", IsNullable=false)]
        public LibrarySoapService.BookModel[] getBooksResponse1;
        
        public getBooksResponse()
        {
        }
        
        public getBooksResponse(LibrarySoapService.BookModel[] getBooksResponse1)
        {
            this.getBooksResponse1 = getBooksResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class updateGenreRequest
    {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class updateGenreResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateGenreRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.updateGenreRequest updateGenreRequest;
        
        public updateGenreRequest1()
        {
        }
        
        public updateGenreRequest1(LibrarySoapService.updateGenreRequest updateGenreRequest)
        {
            this.updateGenreRequest = updateGenreRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateGenreResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.updateGenreResponse updateGenreResponse;
        
        public updateGenreResponse1()
        {
        }
        
        public updateGenreResponse1(LibrarySoapService.updateGenreResponse updateGenreResponse)
        {
            this.updateGenreResponse = updateGenreResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class addAuthorRequest
    {
        
        private AuthorModel authorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuthorModel author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class addAuthorResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAuthorRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.addAuthorRequest addAuthorRequest;
        
        public addAuthorRequest1()
        {
        }
        
        public addAuthorRequest1(LibrarySoapService.addAuthorRequest addAuthorRequest)
        {
            this.addAuthorRequest = addAuthorRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAuthorResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.addAuthorResponse addAuthorResponse;
        
        public addAuthorResponse1()
        {
        }
        
        public addAuthorResponse1(LibrarySoapService.addAuthorResponse addAuthorResponse)
        {
            this.addAuthorResponse = addAuthorResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class deleteGenreRequest
    {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class deleteGenreResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteGenreRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.deleteGenreRequest deleteGenreRequest;
        
        public deleteGenreRequest1()
        {
        }
        
        public deleteGenreRequest1(LibrarySoapService.deleteGenreRequest deleteGenreRequest)
        {
            this.deleteGenreRequest = deleteGenreRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteGenreResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.deleteGenreResponse deleteGenreResponse;
        
        public deleteGenreResponse1()
        {
        }
        
        public deleteGenreResponse1(LibrarySoapService.deleteGenreResponse deleteGenreResponse)
        {
            this.deleteGenreResponse = deleteGenreResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class updateAuthorRequest
    {
        
        private AuthorModel authorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuthorModel author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class updateAuthorResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAuthorRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.updateAuthorRequest updateAuthorRequest;
        
        public updateAuthorRequest1()
        {
        }
        
        public updateAuthorRequest1(LibrarySoapService.updateAuthorRequest updateAuthorRequest)
        {
            this.updateAuthorRequest = updateAuthorRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAuthorResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.updateAuthorResponse updateAuthorResponse;
        
        public updateAuthorResponse1()
        {
        }
        
        public updateAuthorResponse1(LibrarySoapService.updateAuthorResponse updateAuthorResponse)
        {
            this.updateAuthorResponse = updateAuthorResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class addGenreRequest
    {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class addGenreResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addGenreRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.addGenreRequest addGenreRequest;
        
        public addGenreRequest1()
        {
        }
        
        public addGenreRequest1(LibrarySoapService.addGenreRequest addGenreRequest)
        {
            this.addGenreRequest = addGenreRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addGenreResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.addGenreResponse addGenreResponse;
        
        public addGenreResponse1()
        {
        }
        
        public addGenreResponse1(LibrarySoapService.addGenreResponse addGenreResponse)
        {
            this.addGenreResponse = addGenreResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class getGenreRequest
    {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.espe.edu.ec/library")]
    public partial class getGenreResponse
    {
        
        private GenreModel genreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GenreModel genre
        {
            get
            {
                return this.genreField;
            }
            set
            {
                this.genreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGenreRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.getGenreRequest getGenreRequest;
        
        public getGenreRequest1()
        {
        }
        
        public getGenreRequest1(LibrarySoapService.getGenreRequest getGenreRequest)
        {
            this.getGenreRequest = getGenreRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGenreResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.espe.edu.ec/library", Order=0)]
        public LibrarySoapService.getGenreResponse getGenreResponse;
        
        public getGenreResponse1()
        {
        }
        
        public getGenreResponse1(LibrarySoapService.getGenreResponse getGenreResponse)
        {
            this.getGenreResponse = getGenreResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface LibraryPortChannel : LibrarySoapService.LibraryPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class LibraryPortClient : System.ServiceModel.ClientBase<LibrarySoapService.LibraryPort>, LibrarySoapService.LibraryPort
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LibraryPortClient() : 
                base(LibraryPortClient.GetDefaultBinding(), LibraryPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.LibraryPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryPortClient(EndpointConfiguration endpointConfiguration) : 
                base(LibraryPortClient.GetBindingForEndpoint(endpointConfiguration), LibraryPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LibraryPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LibraryPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.addBookResponse1> LibrarySoapService.LibraryPort.addBookAsync(LibrarySoapService.addBookRequest1 request)
        {
            return base.Channel.addBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.addBookResponse1> addBookAsync(LibrarySoapService.addBookRequest addBookRequest)
        {
            LibrarySoapService.addBookRequest1 inValue = new LibrarySoapService.addBookRequest1();
            inValue.addBookRequest = addBookRequest;
            return ((LibrarySoapService.LibraryPort)(this)).addBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.deleteAuthorResponse1> LibrarySoapService.LibraryPort.deleteAuthorAsync(LibrarySoapService.deleteAuthorRequest1 request)
        {
            return base.Channel.deleteAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.deleteAuthorResponse1> deleteAuthorAsync(LibrarySoapService.deleteAuthorRequest deleteAuthorRequest)
        {
            LibrarySoapService.deleteAuthorRequest1 inValue = new LibrarySoapService.deleteAuthorRequest1();
            inValue.deleteAuthorRequest = deleteAuthorRequest;
            return ((LibrarySoapService.LibraryPort)(this)).deleteAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.getGenresResponse> LibrarySoapService.LibraryPort.getGenresAsync(LibrarySoapService.getGenresRequest1 request)
        {
            return base.Channel.getGenresAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.getGenresResponse> getGenresAsync(LibrarySoapService.getGenresRequest getGenresRequest)
        {
            LibrarySoapService.getGenresRequest1 inValue = new LibrarySoapService.getGenresRequest1();
            inValue.getGenresRequest = getGenresRequest;
            return ((LibrarySoapService.LibraryPort)(this)).getGenresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.getBookResponse1> LibrarySoapService.LibraryPort.getBookAsync(LibrarySoapService.getBookRequest1 request)
        {
            return base.Channel.getBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.getBookResponse1> getBookAsync(LibrarySoapService.getBookRequest getBookRequest)
        {
            LibrarySoapService.getBookRequest1 inValue = new LibrarySoapService.getBookRequest1();
            inValue.getBookRequest = getBookRequest;
            return ((LibrarySoapService.LibraryPort)(this)).getBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.updateBookResponse1> LibrarySoapService.LibraryPort.updateBookAsync(LibrarySoapService.updateBookRequest1 request)
        {
            return base.Channel.updateBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.updateBookResponse1> updateBookAsync(LibrarySoapService.updateBookRequest updateBookRequest)
        {
            LibrarySoapService.updateBookRequest1 inValue = new LibrarySoapService.updateBookRequest1();
            inValue.updateBookRequest = updateBookRequest;
            return ((LibrarySoapService.LibraryPort)(this)).updateBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.getAuthorsResponse> LibrarySoapService.LibraryPort.getAuthorsAsync(LibrarySoapService.getAuthorsRequest1 request)
        {
            return base.Channel.getAuthorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.getAuthorsResponse> getAuthorsAsync(LibrarySoapService.getAuthorsRequest getAuthorsRequest)
        {
            LibrarySoapService.getAuthorsRequest1 inValue = new LibrarySoapService.getAuthorsRequest1();
            inValue.getAuthorsRequest = getAuthorsRequest;
            return ((LibrarySoapService.LibraryPort)(this)).getAuthorsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.deleteBookResponse1> LibrarySoapService.LibraryPort.deleteBookAsync(LibrarySoapService.deleteBookRequest1 request)
        {
            return base.Channel.deleteBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.deleteBookResponse1> deleteBookAsync(LibrarySoapService.deleteBookRequest deleteBookRequest)
        {
            LibrarySoapService.deleteBookRequest1 inValue = new LibrarySoapService.deleteBookRequest1();
            inValue.deleteBookRequest = deleteBookRequest;
            return ((LibrarySoapService.LibraryPort)(this)).deleteBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.getAuthorResponse1> LibrarySoapService.LibraryPort.getAuthorAsync(LibrarySoapService.getAuthorRequest1 request)
        {
            return base.Channel.getAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.getAuthorResponse1> getAuthorAsync(LibrarySoapService.getAuthorRequest getAuthorRequest)
        {
            LibrarySoapService.getAuthorRequest1 inValue = new LibrarySoapService.getAuthorRequest1();
            inValue.getAuthorRequest = getAuthorRequest;
            return ((LibrarySoapService.LibraryPort)(this)).getAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.getBooksResponse> LibrarySoapService.LibraryPort.getBooksAsync(LibrarySoapService.getBooksRequest1 request)
        {
            return base.Channel.getBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.getBooksResponse> getBooksAsync(LibrarySoapService.getBooksRequest getBooksRequest)
        {
            LibrarySoapService.getBooksRequest1 inValue = new LibrarySoapService.getBooksRequest1();
            inValue.getBooksRequest = getBooksRequest;
            return ((LibrarySoapService.LibraryPort)(this)).getBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.updateGenreResponse1> LibrarySoapService.LibraryPort.updateGenreAsync(LibrarySoapService.updateGenreRequest1 request)
        {
            return base.Channel.updateGenreAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.updateGenreResponse1> updateGenreAsync(LibrarySoapService.updateGenreRequest updateGenreRequest)
        {
            LibrarySoapService.updateGenreRequest1 inValue = new LibrarySoapService.updateGenreRequest1();
            inValue.updateGenreRequest = updateGenreRequest;
            return ((LibrarySoapService.LibraryPort)(this)).updateGenreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.addAuthorResponse1> LibrarySoapService.LibraryPort.addAuthorAsync(LibrarySoapService.addAuthorRequest1 request)
        {
            return base.Channel.addAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.addAuthorResponse1> addAuthorAsync(LibrarySoapService.addAuthorRequest addAuthorRequest)
        {
            LibrarySoapService.addAuthorRequest1 inValue = new LibrarySoapService.addAuthorRequest1();
            inValue.addAuthorRequest = addAuthorRequest;
            return ((LibrarySoapService.LibraryPort)(this)).addAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.deleteGenreResponse1> LibrarySoapService.LibraryPort.deleteGenreAsync(LibrarySoapService.deleteGenreRequest1 request)
        {
            return base.Channel.deleteGenreAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.deleteGenreResponse1> deleteGenreAsync(LibrarySoapService.deleteGenreRequest deleteGenreRequest)
        {
            LibrarySoapService.deleteGenreRequest1 inValue = new LibrarySoapService.deleteGenreRequest1();
            inValue.deleteGenreRequest = deleteGenreRequest;
            return ((LibrarySoapService.LibraryPort)(this)).deleteGenreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.updateAuthorResponse1> LibrarySoapService.LibraryPort.updateAuthorAsync(LibrarySoapService.updateAuthorRequest1 request)
        {
            return base.Channel.updateAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.updateAuthorResponse1> updateAuthorAsync(LibrarySoapService.updateAuthorRequest updateAuthorRequest)
        {
            LibrarySoapService.updateAuthorRequest1 inValue = new LibrarySoapService.updateAuthorRequest1();
            inValue.updateAuthorRequest = updateAuthorRequest;
            return ((LibrarySoapService.LibraryPort)(this)).updateAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.addGenreResponse1> LibrarySoapService.LibraryPort.addGenreAsync(LibrarySoapService.addGenreRequest1 request)
        {
            return base.Channel.addGenreAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.addGenreResponse1> addGenreAsync(LibrarySoapService.addGenreRequest addGenreRequest)
        {
            LibrarySoapService.addGenreRequest1 inValue = new LibrarySoapService.addGenreRequest1();
            inValue.addGenreRequest = addGenreRequest;
            return ((LibrarySoapService.LibraryPort)(this)).addGenreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySoapService.getGenreResponse1> LibrarySoapService.LibraryPort.getGenreAsync(LibrarySoapService.getGenreRequest1 request)
        {
            return base.Channel.getGenreAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySoapService.getGenreResponse1> getGenreAsync(LibrarySoapService.getGenreRequest getGenreRequest)
        {
            LibrarySoapService.getGenreRequest1 inValue = new LibrarySoapService.getGenreRequest1();
            inValue.getGenreRequest = getGenreRequest;
            return ((LibrarySoapService.LibraryPort)(this)).getGenreAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LibraryPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LibraryPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/ws");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LibraryPortClient.GetBindingForEndpoint(EndpointConfiguration.LibraryPortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LibraryPortClient.GetEndpointAddress(EndpointConfiguration.LibraryPortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            LibraryPortSoap11,
        }
    }
}
